name: xmas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^4.0.3
  intl: ^0.16.0
  flare_flutter: ^1.5.7

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bayern.csv
    - assets/background.png
    - assets/snow.flr

  fonts:
    - family: Christmas
      fonts:
        - asset: fonts/MountainsofChristmas-Regular.ttf
    - family: Christmas-Bold
      fonts:
        - asset: fonts/MountainsofChristmas-Bold.ttf
    - family: Varela
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
